name: check-docstring-coverage

on: [push]

jobs:
  check-coverage:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: JackMcKew/python-interrogate-check@main
        with:
          path: './scarf'

