name: check-docstring-coverage

on: [push]

jobs:
  pwd:

    runs-on: ubuntu-latest

    steps:
    - run: 'pwd'
  ls:

    runs-on: ubuntu-latest

    steps:
    - run: 'ls -la'
  ls-workspace:

    runs-on: ubuntu-latest

    steps:
    - run: 'ls $GITHUB_WORKSPACE'
  interrogate:

    runs-on: ubuntu-latest

    steps:
    - uses: JackMcKew/python-interrogate-check@main
      with:
        path: '/home/runner/work/scarf-1/scarf-1/scarf/'

