name: check-docstring-coverage

on: [push]

jobs:
  interrogate:

    runs-on: ubuntu-latest

    steps:
    - uses: JackMcKew/python-interrogate-check@main
      with:
        path: '/home/runner/work/scarf-1/scarf-1/scarf/'

