name: check-docstring-coverage

on: [push]

jobs:
  interrogate:

    runs-on: ubuntu-latest

    steps:
    - uses: JackMcKew/python-interrogate-check@main
      with:
        path: '$GITHUB_WORKSPACE/scarf/'

