name: check-docstring-coverage

on: [push]

jobs:
  checkout-repo:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
          ref: 'docstrings'
  ls:

    runs-on: ubuntu-latest

    steps:
    - run: 'ls -la'
  ls-workspace:

    runs-on: ubuntu-latest

    steps:
    - run: 'ls $GITHUB_WORKSPACE'
  interrogate:

    runs-on: ubuntu-latest

    steps:
    - uses: JackMcKew/python-interrogate-check@main
      with:
        path: '$GITHUB_WORKSPACE/scarf'

