name: check-docstring-coverage

on: [push]

jobs:
  check-coverage:

    runs-on: ubuntu-latest

    steps:

      - if: ${{ !env.ACT }}
        name: checkout
        uses: actions/checkout@v2
        with:
          ref: 'docstrings'

      - if: ${{ env.ACT }}
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

          #- uses: JackMcKew/python-interrogate-check@main
      - uses: razofz/python-interrogate-check@main
        with:
          path: './scarf'
          ignore-nested-classes: true
          ignore-private: true
          ignore-semiprivate: true
          ignore-magic: true

